- name: Install packages
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - mc
    - zsh
    - vim
    - sudo
    - wget
    - tmux
    - htop
    - iftop

- name: Create user
  user: name={{ user }} shell='/bin/zsh' groups='sudo'
  sudo: yes

- name: Copy ssh key
  authorized_key: user={{ user }} key='ssh-rsa id_rsa.pub'
  sudo: no

- name: Clone oh-my-zsh
  git: repo='git://github.com/robbyrussell/oh-my-zsh.git'
       dest='/home/{{ user }}/.oh-my-zsh'
       accept_hostkey='yes'
  sudo: no

- name: Copy default rc
  copy: src='vimrc' dest='/home/{{ user }}/.vimrc' owner={{ user }}
  sudo: no

- name: Setup zshrc
  template: src='zshrc' dest='/home/{{ user }}/.zshrc'
  sudo: no

