- name: Install packages apt
  apt: pkg={{ item }}
  sudo: yes
  with_items:
    - mc
    - git
    - vim
    - zsh
    - sudo
    - wget
    - tmux
    - htop
    - iftop
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install packages yum
  yum: pkg={{ item }}
  sudo: yes
  with_items:
    - mc
    - git
    - vim
    - zsh
    - sudo
    - wget
    - tmux
    - htop
    - iftop
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Install pip
  shell: wget --no-check-certificate -O - https://bootstrap.pypa.io/get-pip.py | python
  args:
    creates: /usr/local/bin/pip
  sudo: yes

- name: Install venv
  pip: name={{ item }}
  sudo: yes
  with_items:
    - virtualenv
    - virtualenvwrapper

- name: Create user
  user: name={{ user }}
        shell=/bin/zsh
        groups=wheel
  sudo: yes

- name: Copy ssh key
  authorized_key: user={{ user }}
                  key="{{ lookup('file', '/Users/vp/.ssh/id_rsa.pub') }}"
  sudo: yes

- name: Clone oh-my-zsh
  git: repo=git://github.com/robbyrussell/oh-my-zsh.git
       dest=/home/{{ user }}/.oh-my-zsh
       accept_hostkey=yes
  sudo: yes

- name: Clone vundle
  git: repo=https://github.com/gmarik/Vundle.vim.git
       dest=/home/{{ user }}/.vim/bundle/Vundle.vim
       accept_hostkey=yes
  sudo: yes

- name: Copy default rc
  copy: src={{ item }}
        dest=/home/{{ user }}/.{{ item }}
  sudo: yes
  with_items:
    - vimrc
    - tmux.conf

- name: Setup zshrc
  template: src=zshrc.j2
            dest=/home/{{ user }}/.zshrc
  sudo: yes

- name: Chown
  file: path=/home/{{ user }}
        owner={{ user }}
        group={{ user }}
        recurse=yes
  sudo: yes
