- name: Download
  shell: wget -O - http://download.redis.io/releases/redis-stable.tar.gz | tar -xz -C /tmp
  args:
    creates: /tmp/redis-stable
  sudo: no

- name: Install
  shell: make install
  args:
    creates: /usr/local/bin/redis-server
    chdir: /tmp/redis-stable
  sudo: yes

- name: Make dirs
  file: path={{ item }}
        state=directory
  sudo: yes
  with_items:
    - /var/redis
    - /etc/redis

- name: Copy config
  copy: src=redis.conf
        dest=/etc/redis/redis.conf
  sudo: yes

- name: Add service
  copy: src=init_script
        dest=/etc/init.d/redis
        mode=755
  sudo: yes

- name: Start
  service: name=redis
           enabled=yes
           state=started
           pattern=redis
  sudo: yes
