- name: Clone
  git: repo={{ repo }}
       dest=/home/{{ user }}/{{ service }}
       accept_hostkey=yes
  sudo: no

- name: Install supervisord
  pip: name=supervisor
       virtualenv=/home/{{ user }}/.virtualenvs/{{ service }}
  sudo: no

- name: Install requirements
  pip: requirements=/home/{{ user }}/{{ service }}/requirements.txt
       virtualenv=/home/{{ user }}/.virtualenvs/{{ service }}
  sudo: no

- name: Make dirs
  file: path={{ item }}
        state=directory
  sudo: no
  with_items:
    - /home/{{ user }}/var/run
    - /home/{{ user }}/var/log

- name: Add service
  template: src=service.j2
            dest=/etc/init.d/{{ service }}
            mode=755
  sudo: yes
